app_name: psc-data-api
group: api
weight: 905
routes:
  1: ^/persons-with-significant-control/healthcheck
  2: ^/company/(.*)/persons-with-significant-control/(.*)/full_record
  3: ^/company/(.*)/persons-with-significant-control/individual/(.*)
  4: ^/company/(.*)/persons-with-significant-control/individual-beneficial-owner/(.*)
  5: ^/company/(.*)/persons-with-significant-control/corporate-entity-beneficial-owner/(.*)
  6: ^/company/(.*)/persons-with-significant-control/legal-person/(.*)
  7: ^/company/(.*)/persons-with-significant-control/corporate-entity/(.*)

