management.endpoints.access.default=${MANAGEMENT_ENDPOINTS_ACCESS_BY_DEFAULT:none}
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.access=${MANAGEMENT_ENDPOINT_HEALTH_ACCESS:read-only}
management.health.mongodb.enabled=false
api.key=${CHS_API_KEY:chsApiKey}
kafka.api.url=${CHS_KAFKA_API_URL:http://localhost:8888}
metrics.api.url=${API_LOCAL_URL:http://localhost:8888}
exemptions.api.url=${API_LOCAL_URL:http://localhost:8888}
spring.mongodb.uri=${MONGODB_URL:mongodb://mongo:27017}
spring.data.mongodb.name=company_pscs
# Disable static resources (otherwise NoResourceFoundException when no handler found)
spring.web.resources.add-mappings=false
# Enable 404 status when no handler found
# This property is deprecated: DispatcherServlet property is deprecated for removal and should no longer need to be configured
# spring.mvc.throw-exception-if-no-handler-found=false
spring.data.jackson.default-property-inclusion=NON_NULL
feature.seeding_collection_enabled=${SEEDING_COLLECTION_ENABLED:false}
psc.links.enabled=${FEATURE_FLAG_PSC_LINKS_ENABLED:true}
server.port=${PORT:8081}